pull_requests:
  do_not_increment_build_number: true
skip_tags: true
clone_depth: 5
nuget:
  account_feed: true
  project_feed: true
before_build:
  - nuget restore D2L.Hypermedia.Siren\D2L.Hypermedia.Siren.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
configuration:
- Release
